title: "D&D Homebrew"
description: "A collection of D&D Homebrew Content."
theme: "just-the-docs"
remote_theme: "just-the-docs/just-the-docs"
search_enabled: true
baseurl: "/DnD-Homebrew"
permalink: /:path/:title/

markdown: kramdown
highlighter: rouge

site_logo: "favicon.svg"

favicon_ico: favicon.ico

color_scheme: dark

cache:
  jekyll: true
  favicon.ico: true
